CREATE TABLE IF NOT EXISTS TURNIRS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    place VARCHAR(255) NOT NULL,
    date timestamp NOT NULL,
    file_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    t_id INT REFERENCES TURNIRS(id),
    category VARCHAR(255) NOT NULL,
    state INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBERS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    c_id INT REFERENCES CATEGORIES(id),
    fio VARCHAR(255) NOT NULL,
    n_fights INT NOT NULL,
    n_wons INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMB_TEL(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_id INT REFERENCES MEMBERS(id),
    tel_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FIGHTS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    num_f INT NOT NULL,
    is_end BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MEMB_FIGH(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    m_id INTEGER REFERENCES MEMBERS(id),
    f_id INTEGER REFERENCES FIGHTS(id)
);

CREATE TABLE IF NOT EXISTS FIGH_FIGH(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    f INTEGER REFERENCES FIGHTS(id),
    f_id INTEGER REFERENCES FIGHTS(id)
)